[env:uno_r4_wifi]
platform = renesas-ra
board = uno_r4_wifi
framework = arduino
monitor_speed = 115200
upload_port = /dev/cu.usbmodem1051DB37C6382
monitor_port = /dev/cu.usbmodem1051DB37C6382

lib_deps =
    bogde/HX711
    arduino-libraries/ArduinoBLE